baseURL = 'https://kamar535.github.io/hugo-gp-test.github.io/2025'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

publishDir = 'public/2025/'

# https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#public-web-server-from-subdirectory
relativeURLs = false

[caches]
    [caches.images]
        dir = ':cacheDir/images'
